# this config file is for installer.71m.us

name: JATOS
image: ubuntu-16-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: jatos
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  package_upgrade: true
  packages:
    - docker
  runcmd:
    - docker pull jatos/jatos:3.1.10
    - docker run -d -p 80:9000 jatos/jatos:3.1.10
