name: JATOS
image: ubuntu-16-04-x64
min_size: 1gb
config:
  #cloud-config
  packages:
    - unzip
  users:
    - name: jatos
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  runcmd:
    - cd /home/jatos/
    - wget https://github.com/JATOS/JATOS/releases/download/v3.1.10/jatos-3.1.10_linux_java.zip
    - unzip jatos-3.1.10_linux_java.zip
    - cd jatos-3.1.10_linux_java
    - su -l jatos -c "nohup ./loader.sh start -Dhttp.port=80 -Dhttp.address=localhost &"
