name: JATOS
image: ubuntu-16-04-x64
min_size: 1gb
packages:
    - unzip
config:
  #cloud-config
  runcmd:
    - wget https://github.com/JATOS/JATOS/releases/download/v3.1.10/jatos-3.1.10_linux_java.zip
    - unzip jatos-3.1.10_linux_java.zip
    - cd jatos-3.1.10_linux_java
    - nohup ./loader.sh start -Dhttp.port=80 &
