version: '3'

# Docker Compose config for JATOS + Traefik with automatic encryption

networks:
  proxy:
    external: true
  internal:
    external: false

services:

  traefik:
    image: traefik:v1.7.18
    command: --docker
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/traefik.toml:/traefik.toml
      - /root/acme.json:/acme.json
    container_name: traefik
    restart: always

  jatos:
    image: jatos/jatos:latest
    networks:
      - internal
      - proxy
    expose:
      - "9000"
    container_name: jatos
    restart: always
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:<DOMAIN_NAME>"
      - "traefik.basic.port=9000"
      - "traefik.basic.protocol=http"
